feat: new format call `Column Files`
apitable/apitable-settings-generator pull request #5
Opened 2022-11-28 11:05 UTC by Pengap

issues: #1

2022-11-28 11:09 UTC, mr-kelly requested changes

2022-11-28 11:09 UTC, mr-kelly commented on tests/main.test.ts
> +    await expect(gen.checkConfigTables(pfConfig.tables)).rejects.toThrow(Error);
make some real test to `/tmp/xxx`

2022-12-01 08:23 UTC, Pengap commented on tests/main.test.ts
> +    await expect(gen.checkConfigTables(pfConfig.tables)).rejects.toThrow(Error);
```suggestion

    it("call format: column-files generated file ok", async () => {
```

2022-12-01 12:15 UTC, mr-kelly approved these changes

2022-12-01 12:15 UTC, mr-kelly commented on tests/main.test.ts
> +      'i18n_strings': {
just {
   "string key" : "string value" 
}

ok?

2022-12-01 16:23 UTC, merged